name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: cd chien-treats && pnpm install --frozen-lockfile
      - name: Lint
        run: cd chien-treats && pnpm lint
      - name: Typecheck
        run: cd chien-treats && pnpm typecheck
      - name: API Lint
        run: cd chien-treats && pnpm api:lint
      - name: API Typecheck
        run: cd chien-treats && pnpm api:typecheck
      - name: API Tests
        run: cd chien-treats && pnpm api:test
      - name: Unit tests
        run: cd chien-treats && pnpm test
      - name: Install Playwright browsers
        run: cd chien-treats && pnpm exec playwright install --with-deps
      - name: E2E tests
        run: cd chien-treats && pnpm test:e2e
